/*
 * OpenBOR - http://www.chronocrash.com
 * -----------------------------------------------------------------------
 * All rights reserved, see LICENSE in OpenBOR root for details.
 *
 * Copyright (c) 2004 - 2014 OpenBOR Team
 */

#ifndef	CONTROL_SWITCH_H
#define	CONTROL_SWITCH_H

#include "joysticks.h"

#define	CONTROL_ESC                 (JOY_LIST_FIRST + 4) + 1    // LSTICK
#define	CONTROL_DEFAULT1_UP         (JOY_LIST_FIRST + 28) + 1   // UP (DIGITAL OR ANALOG)
#define	CONTROL_DEFAULT1_RIGHT      (JOY_LIST_FIRST + 31) + 1   // RIGHT (DIGITAL OR ANALOG)
#define	CONTROL_DEFAULT1_DOWN       (JOY_LIST_FIRST + 29) + 1   // DOWN (DIGITAL OR ANALOG)
#define	CONTROL_DEFAULT1_LEFT       (JOY_LIST_FIRST + 30) + 1   // LEFT (DIGITAL OR ANALOG)
#define	CONTROL_DEFAULT1_FIRE1      (JOY_LIST_FIRST + 0) + 1    // A
#define	CONTROL_DEFAULT1_FIRE2      (JOY_LIST_FIRST + 1) + 1    // B
#define	CONTROL_DEFAULT1_FIRE3      (JOY_LIST_FIRST + 6) + 1    // L
#define	CONTROL_DEFAULT1_FIRE4      (JOY_LIST_FIRST + 7) + 1    // R
#define	CONTROL_DEFAULT1_FIRE5      (JOY_LIST_FIRST + 2) + 1    // X
#define	CONTROL_DEFAULT1_FIRE6      (JOY_LIST_FIRST + 3) + 1    // Y
#define	CONTROL_DEFAULT1_START      (JOY_LIST_FIRST + 10) + 1   // PLUS (OR MINUS)
#define	CONTROL_DEFAULT1_SCREENSHOT (JOY_LIST_FIRST + 5) + 1    // RSTICK
#define	CONTROL_DEFAULT1_ESC        (JOY_LIST_FIRST + 4) + 1    // MINUS

#define	CONTROL_DEFAULT2_UP			(CONTROL_DEFAULT1_UP + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_RIGHT		(CONTROL_DEFAULT1_RIGHT + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_DOWN		(CONTROL_DEFAULT1_DOWN + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_LEFT		(CONTROL_DEFAULT1_LEFT + JOY_MAX_INPUTS)
#define CONTROL_DEFAULT2_FIRE1		(CONTROL_DEFAULT1_FIRE1 + JOY_MAX_INPUTS)
#define CONTROL_DEFAULT2_FIRE2		(CONTROL_DEFAULT1_FIRE2 + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_FIRE3		(CONTROL_DEFAULT1_FIRE3 + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_FIRE4		(CONTROL_DEFAULT1_FIRE4 + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_FIRE5		(CONTROL_DEFAULT1_FIRE5 + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_FIRE6		(CONTROL_DEFAULT1_FIRE6 + JOY_MAX_INPUTS)
#define CONTROL_DEFAULT2_START		(CONTROL_DEFAULT1_START + JOY_MAX_INPUTS)
#define CONTROL_DEFAULT2_SCREENSHOT (CONTROL_DEFAULT1_SCREENSHOT + JOY_MAX_INPUTS)
#define	CONTROL_DEFAULT2_ESC        (CONTROL_DEFAULT1_ESC + JOY_MAX_INPUTS)

#define	CONTROL_DEFAULT3_UP			(CONTROL_DEFAULT1_UP + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_RIGHT		(CONTROL_DEFAULT1_RIGHT + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_DOWN		(CONTROL_DEFAULT1_DOWN + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_LEFT		(CONTROL_DEFAULT1_LEFT + (JOY_MAX_INPUTS * 2))
#define CONTROL_DEFAULT3_FIRE1		(CONTROL_DEFAULT1_FIRE1 + (JOY_MAX_INPUTS * 2))
#define CONTROL_DEFAULT3_FIRE2		(CONTROL_DEFAULT1_FIRE2 + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_FIRE3		(CONTROL_DEFAULT1_FIRE3 + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_FIRE4		(CONTROL_DEFAULT1_FIRE4 + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_FIRE5		(CONTROL_DEFAULT1_FIRE5 + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_FIRE6		(CONTROL_DEFAULT1_FIRE6 + (JOY_MAX_INPUTS * 2))
#define CONTROL_DEFAULT3_START		(CONTROL_DEFAULT1_START + (JOY_MAX_INPUTS * 2))
#define CONTROL_DEFAULT3_SCREENSHOT (CONTROL_DEFAULT1_SCREENSHOT + (JOY_MAX_INPUTS * 2))
#define	CONTROL_DEFAULT3_ESC        (CONTROL_DEFAULT1_ESC + (JOY_MAX_INPUTS * 2))

#define	CONTROL_DEFAULT4_UP			(CONTROL_DEFAULT1_UP + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_RIGHT		(CONTROL_DEFAULT1_RIGHT + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_DOWN		(CONTROL_DEFAULT1_DOWN + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_LEFT		(CONTROL_DEFAULT1_LEFT + (JOY_MAX_INPUTS * 3))
#define CONTROL_DEFAULT4_FIRE1		(CONTROL_DEFAULT1_FIRE1 + (JOY_MAX_INPUTS * 3))
#define CONTROL_DEFAULT4_FIRE2		(CONTROL_DEFAULT1_FIRE2 + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_FIRE3		(CONTROL_DEFAULT1_FIRE3 + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_FIRE4		(CONTROL_DEFAULT1_FIRE4 + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_FIRE5		(CONTROL_DEFAULT1_FIRE5 + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_FIRE6		(CONTROL_DEFAULT1_FIRE6 + (JOY_MAX_INPUTS * 3))
#define CONTROL_DEFAULT4_START		(CONTROL_DEFAULT1_START + (JOY_MAX_INPUTS * 3))
#define CONTROL_DEFAULT4_SCREENSHOT (CONTROL_DEFAULT1_SCREENSHOT + (JOY_MAX_INPUTS * 3))
#define	CONTROL_DEFAULT4_ESC        (CONTROL_DEFAULT1_ESC + (JOY_MAX_INPUTS * 3))

#endif // CONTROL_SWITCH_H