#!/bin/sh
# Name: paxplode
# Author: Plombo
# Frontend for borpak that emulates the "paxplode" utility.
# Put this file in the same directory as the borpak executable.

NUMPARAMS=1
#DIR=`dirname "$0"`

if [ $# -eq "$NUMPARAMS" ]
then
  #"$DIR/borpak" "$@"
  borpak "$@"
else
  echo "Usage: paxplode pakfile"
fi

exit 0
