/*
 * OpenBOR - http://www.chronocrash.com
 * -----------------------------------------------------------------------
 * All rights reserved. See LICENSE in OpenBOR root for license details.
 *
 * Copyright (c) 2004 OpenBOR Team
 */

/*
* Caskey, Damon V.*
* 2023-03-03
* 
* Model Properties
*/
typedef enum e_model_properties
{
	MODEL_PROPERTY_ACTION_FREEZE,
	MODEL_PROPERTY_AIR_CONTROL,
	MODEL_PROPERTY_ANTI_GRAVITY,
	MODEL_PROPERTY_BLEND_MODE,
	MODEL_PROPERTY_BLOCK_CONFIG_FLAGS,
	MODEL_PROPERTY_BLOCK_ODDS,
	MODEL_PROPERTY_BLOCK_PAIN,
	MODEL_PROPERTY_BLOCK_THRESHOLD,
	MODEL_PROPERTY_BOUNCE,
	MODEL_PROPERTY_CHILD_FOLLOW,
	MODEL_PROPERTY_COLORSET,
	MODEL_PROPERTY_DEATH_CONFIG_FLAGS,
	MODEL_PROPERTY_ENHANCED_DELAY_CAP_MAX,
	MODEL_PROPERTY_ENHANCED_DELAY_CAP_MIN,
	MODEL_PROPERTY_ENHANCED_DELAY_MODIFIER,
	MODEL_PROPERTY_ENHANCED_DELAY_MULTIPLIER,
	MODEL_PROPERTY_ENHANCED_DELAY_RANGE_MAX,
	MODEL_PROPERTY_ENHANCED_DELAY_RANGE_MIN,
	MODEL_PROPERTY_FACTION,
	MODEL_PROPERTY_FLIP,
	MODEL_PROPERTY_GROUND,
	MODEL_PROPERTY_GUARD_POINTS,
	MODEL_PROPERTY_GUARD_RATE,
	MODEL_PROPERTY_HP,
	MODEL_PROPERTY_HUD_DISABLE,
	MODEL_PROPERTY_HUD_POPUP,
	MODEL_PROPERTY_ICON,
	MODEL_PROPERTY_INDEX,
	MODEL_PROPERTY_LAYER,
	MODEL_PROPERTY_MAKE_INVINCIBLE,
	MODEL_PROPERTY_MOVE_CONFIG_FLAGS,
	MODEL_PROPERTY_MP,
	MODEL_PROPERTY_MULTIPLE,
	MODEL_PROPERTY_NAME,
	MODEL_PROPERTY_OFF_SCREEN_KILL,
	MODEL_PROPERTY_OFF_SCREEN_NO_ATTACK,
	MODEL_PROPERTY_PAIN_CONFIG_FLAGS,
	MODEL_PROPERTY_PATH,
	MODEL_PROPERTY_PRIORITY,
	MODEL_PROPERTY_QUAKE_CONFIG,
	MODEL_PROPERTY_RISE_INVINCIBLE,
	MODEL_PROPERTY_RUN_CONFIG_FLAGS,
	MODEL_PROPERTY_RUN_JUMP_HEIGHT,
	MODEL_PROPERTY_RUN_JUMP_LENGTH,
	MODEL_PROPERTY_RUN_SPEED,
	MODEL_PROPERTY_SCORE,
	MODEL_PROPERTY_SCROLL,
	MODEL_PROPERTY_SHADOW_CONFIG_FLAGS,
	MODEL_PROPERTY_SHADOW_INDEX,
	MODEL_PROPERTY_SPAWN_HUD,
	MODEL_PROPERTY_SUBTYPE,
	MODEL_PROPERTY_TYPE,
	MODEL_PROPERTY_WEAPON,
	MODEL_PROPERTY_TEST_FIXED,
	MODEL_PROPERTY_TEST_POINTER,
	MODEL_PROPERTY_END
} e_model_properties;


HRESULT openbor_get_model_property(const ScriptVariant* const* varlist, ScriptVariant** const pretvar, const int paramCount);
HRESULT openbor_set_model_property(ScriptVariant **varlist, ScriptVariant** const pretvar, const int paramCount);