apply plugin: 'com.android.application'

android {
  compileSdkVersion 35
    defaultConfig {
      minSdkVersion 21
        targetSdkVersion 35

        //////////// MODFY FOR CUSTOM APK /////////////////
        applicationId "org.openbor.engine"
        namespace "org.openbor.engine"
        versionCode 1
        versionName "1.0.0"
        resValue "string", "app_name", "Openbor"
        ///////////////////////////////////////////////////

        externalNativeBuild {
          ndkBuild {
              abiFilters 'arm64-v8a'
          }
        }
    }

  signingConfigs {
        debug {
        // ... your debug keystore details here ...
        // For example, if you have a debug.keystore in your project root
        storeFile file('debug.keystore')
        storePassword 'android' // Default password for debug keystore
        keyAlias 'androiddebugkey' // Default alias
        keyPassword 'android' // Default password for alias
    }
    
    release {
      // only try to find keystore.properties when it's release build
      /*
        def keystorePropertiesFile = rootProject.file("keystore.properties")
        def keystoreProperties = new Properties()
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile file(keystoreProperties['storeFile'])
        storePassword keystoreProperties['storePassword']
        */
    } 
  }

  buildTypes {
  
  android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "OpenBOR.apk";
		}
	}
     debug {
        // Do NOT add 'signingConfig signingConfigs.release' here
        // It should inherit the default debug signing or you define 'signingConfig signingConfigs.debug'
    }
    release {
      minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        signingConfig signingConfigs.release
    }
  }

  if (!project.hasProperty('EXCLUDE_NATIVE_LIBS')) {
    sourceSets.main {
      jniLibs.srcDir 'libs'
    }
    externalNativeBuild {
      ndkBuild {
        path 'jni/Android.mk'
      }
    }

  }

  lintOptions {
    abortOnError false
  }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    ndkVersion '21.4.7075529'
    buildToolsVersion '36.0.0'
}

dependencies {
  implementation fileTree(include: ['*.jar'], dir: 'libs')
  implementation 'androidx.appcompat:appcompat:1.0.2'
  implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
  //needed to fix sdk 34+ crashing
  implementation 'org.jetbrains:annotations:16.0.2'
}